export const CSS_PROPERTY_VALUES: Record<string, string[]> = {
  display: [
    'block',
    'inline',
    'inline-block',
    'flex',
    'inline-flex',
    'grid',
    'inline-grid',
    'none',
    'contents',
    'table',
    'list-item',
    'flow-root',
  ],
  position: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
  'flex-direction': ['row', 'row-reverse', 'column', 'column-reverse'],
  'flex-wrap': ['nowrap', 'wrap', 'wrap-reverse'],
  'justify-content': [
    'flex-start',
    'flex-end',
    'center',
    'space-between',
    'space-around',
    'space-evenly',
    'start',
    'end',
    'left',
    'right',
    'normal',
    'stretch',
  ],
  'justify-items': ['start', 'end', 'center', 'stretch', 'normal'],
  'align-items': ['stretch', 'flex-start', 'flex-end', 'center', 'baseline', 'normal', 'start', 'end'],
  'align-content': [
    'flex-start',
    'flex-end',
    'center',
    'space-between',
    'space-around',
    'space-evenly',
    'stretch',
    'normal',
  ],
  'align-self': ['auto', 'flex-start', 'flex-end', 'center', 'baseline', 'stretch', 'normal'],
  'text-align': ['left', 'right', 'center', 'justify', 'start', 'end'],
  'text-decoration-line': ['none', 'underline', 'overline', 'line-through'],
  'text-decoration': ['none', 'underline', 'overline', 'line-through'],
  'text-transform': ['none', 'capitalize', 'uppercase', 'lowercase', 'full-width'],
  'text-overflow': ['clip', 'ellipsis'],
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'clip'],
  'overflow-x': ['visible', 'hidden', 'scroll', 'auto', 'clip'],
  'overflow-y': ['visible', 'hidden', 'scroll', 'auto', 'clip'],
  'white-space': ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line', 'break-spaces'],
  cursor: [
    'auto',
    'default',
    'pointer',
    'wait',
    'text',
    'move',
    'not-allowed',
    'grab',
    'grabbing',
    'crosshair',
    'help',
    'zoom-in',
    'zoom-out',
    'ns-resize',
    'ew-resize',
  ],
  'font-weight': ['normal', 'bold', 'bolder', 'lighter', '100', '200', '300', '400', '500', '600', '700', '800', '900'],
  'font-style': ['normal', 'italic', 'oblique'],
  visibility: ['visible', 'hidden', 'collapse'],
  'box-sizing': ['content-box', 'border-box'],
  'border-style': ['none', 'solid', 'dashed', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset', 'hidden'],
  'background-repeat': ['repeat', 'repeat-x', 'repeat-y', 'no-repeat', 'space', 'round'],
  'background-size': ['auto', 'cover', 'contain'],
  'background-position': ['left', 'right', 'top', 'bottom', 'center'],
  'background-attachment': ['scroll', 'fixed', 'local'],
  'list-style-type': [
    'none',
    'disc',
    'circle',
    'square',
    'decimal',
    'decimal-leading-zero',
    'lower-roman',
    'upper-roman',
    'lower-alpha',
    'upper-alpha',
  ],
  float: ['left', 'right', 'none'],
  clear: ['left', 'right', 'both', 'none'],
  'pointer-events': ['auto', 'none'],
  'object-fit': ['fill', 'contain', 'cover', 'none', 'scale-down'],
  'vertical-align': ['baseline', 'top', 'middle', 'bottom', 'text-top', 'text-bottom', 'sub', 'super'],
  resize: ['none', 'both', 'horizontal', 'vertical'],
  'table-layout': ['auto', 'fixed'],
  'word-break': ['normal', 'break-all', 'keep-all', 'break-word'],
  'animation-direction': ['normal', 'reverse', 'alternate', 'alternate-reverse'],
  'animation-fill-mode': ['none', 'forwards', 'backwards', 'both'],
  'animation-timing-function': ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out', 'step-start', 'step-end'],
  'transition-timing-function': ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out', 'step-start', 'step-end'],
  'mix-blend-mode': [
    'normal',
    'multiply',
    'screen',
    'overlay',
    'darken',
    'lighten',
    'color-dodge',
    'color-burn',
    'difference',
    'exclusion',
    'hue',
    'saturation',
    'color',
    'luminosity',
  ],
};
